/* ----------------------------------------------------------------------
   Title:           project_tim_specs.spec
   Generated By:    ATEGen
                    Version: 1.15.1 [linux x86_64_RHEL7] 31-Jan-2025
   User:            pod_te
   Generation Date: Mon May  5 13:52:14 2025
   Source File:     AllRefClkPins10ns_diff.stil Mon May  5 13:48:10 2025
---------------------------------------------------------------------- */
import Timings.galbal.AllRefClkPins10ns_diff_wvt;
import Timings.galbal.AllRefClkPins10ns_diff_tim_spec_decl;
import Timings.galbal.AllRefClkPins10ns_diff_tim;
import configuration.IO_Group;
spec project_tim_specs {
    per_AllRefClkPins10ns_wvt = 10.000000 ns;
    Ratio= 1.0;
}
