/* ----------------------------------------------------------------------
   Title:           project_tim.spec
   Generated By:    ATEGen
                    Version: 1.15.1 [linux x86_64_RHEL7] 31-Jan-2025
   User:            pod_te
   Generation Date: Mon May  5 13:52:14 2025
   Source File:     AllRefClkPins10ns_diff.stil Mon May  5 13:48:10 2025
---------------------------------------------------------------------- */
import Timings.galbal.AllRefClkPins10ns_diff_tim_spec_decl;
import configuration.IO_Group;
spec AllRefClkPins10ns_diff_tim_spec_decl {
    set AllRefClkPins10ns_timing_AllRefClkPins10ns_wvt;
    setup digInOut pad_pcie1_refclk100_1_n + pad_top_d2ds_phy2_refclk100_p + pad_top_d2ds_phy4_refclk100_p + pad_top_d2ds_phy4_refclk100_n + pad_top_d2ds_phy2_refclk100_n + pad_pcie1_refclk100_1_p + pad_top_d2ds_phy0_refclk100_n + pad_top_d2ds_phy3_refclk100_n + pad_pcie1_refclk100_0_p + pad_pcie0_refclk100_3_p + pad_pcie0_refclk100_0_p + pad_ams_pdp_0_pad_refclk_n + pad_pcie1_refclk100_3_p + pad_pcie1_refclk100_2_n + pad_ams_pdp_1_pad_refclk_p + pad_top_d2ds_phy1_refclk100_n + pad_pcie1_refclk100_2_p + pad_ams_pdp_1_pad_refclk_n + pad_top_d2ds_phy3_refclk100_p + pad_ams_pdp_0_pad_refclk_p + pad_pcie0_refclk100_3_n + pad_pcie1_refclk100_0_n + pad_top_d2ds_phy0_refclk100_p + pad_pcie0_refclk100_2_n + pad_refclk_100_n + pad_pcie0_refclk100_1_p + pad_refclk_100_spare_n + pad_pcie1_refclk100_3_n + pad_top_d2ds_phy1_refclk100_p + pad_refclk_100_spare_p + pad_pcie0_refclk100_1_n + pad_refclk_100_p + pad_pcie0_refclk100_0_n + pad_pcie0_refclk100_2_p {
        set timing AllRefClkPins10ns_timing_AllRefClkPins10ns_wvt {
            period = per_AllRefClkPins10ns_wvt *Ratio;
            d1 = 0.0 *per_AllRefClkPins10ns_wvt *Ratio;
            d2 = 0.5 *per_AllRefClkPins10ns_wvt *Ratio;
            r1 = 0.9 *per_AllRefClkPins10ns_wvt *Ratio;
        }
    }
}
