/* ----------------------------------------------------------------------
   Title:           project_tim_spec_decl.spec
   Generated By:    ATEGen
                    Version: 1.15.1 [linux x86_64_RHEL7] 31-Jan-2025
   User:            pod_te
   Generation Date: Mon May  5 13:52:14 2025
   Source File:     AllRefClkPins10ns_diff.stil Mon May  5 13:48:10 2025
---------------------------------------------------------------------- */
import configuration.IO_Group;
import Timings.global.TimingRatio;
spec AllRefClkPins10ns_diff_spec_decl {
    var Time per_AllRefClkPins10ns;
}
